from typing import Tuple


def VikeyFind() -> Tuple[int, int]: ...


def VikeyGetHID(index: int) -> Tuple[int, int]: ...


def VikeyGetSoftIDString(index: int) -> Tuple[int, str]: ...


def VikeyGetType(index: int) -> Tuple[int, int]: ...


def VikeyGetLevel(index: int) -> Tuple[int, int]: ...


def VikeyGetPtroductName(index: int) -> Tuple[int, str]: ...


def ViKeyRandom(index: int) -> Tuple[int, list]: ...


def VikeyMD5(data: bytes, length: int, index: int) -> Tuple[int, bytes]: ...


def VikeySHA1(data: bytes, length: int, index: int) -> Tuple[int, bytes]: ...


def VikeyHmacMD5(data: bytes, length: int, index: int) -> Tuple[int, bytes]: ...


def VikeyHmacSHA1(data: bytes, length: int, index: int) -> Tuple[int, bytes]: ...


def VikeyUserLogin(password: bytes, index: int) -> Tuple[int, int]: ...


def VikeyAdminLogin(password: bytes, index: int) -> Tuple[int, int]: ...


def VikeyLogout(index: int) -> Tuple[int, int]: ...
